version: '3'
services:
  webapp:
    image: node:alpine3.11
    container_name: calculator-api-webapp
    ports:
      - 3000
    environment:
      NODE_ENV: production
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: "calculator.random21.com"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: "npm start"

networks:
  default:
    external: 
      name: nginx-proxy