version: '3'
services:
  webapp:
    image: node:alpine3.11
    container_name: calcaulator-api-webapp
    ports:
     - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: "npm run start:dev"